---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8s-ansible-mysql
  labels:
    app: k8s-ansible
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
