---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: amz-selenium-web-redis
  labels:
    app: amz-selenium-web
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
