---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8s-ansible-uploads
  labels:
    app: k8s-ansible
    component: uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
