---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amz-selenium-web-puma
  labels:
    app: amz-selenium-web
    component: puma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amz-selenium-web
      component: puma
  template:
    metadata:
      labels:
        app: amz-selenium-web
        component: puma
    spec:
      restartPolicy: Always
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: amz-selenium-web-uploads
      containers:
        - name: puma
          image: wellsmuke/amz_selenium_web:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          command:
            - ./kube/bin/start-puma
          # livenessProbe:
          #   httpGet:
          #     path: /health_check/full
          #     port: 3000
          #   initialDelaySeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /health_check/full
          #     port: 3000
          #   initialDelaySeconds: 30
          envFrom:
            - configMapRef:
                name: amz-selenium-web-rails-env
            - secretRef:
                name: amz-selenium-web-rails-env
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/public/uploads
      imagePullSecrets:
      - name: docker-registry
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - amz-selenium-web
              - key: component
                operator: In
                values:
                - puma
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - amz-selenium-web
              - key: component
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
