---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-mysql
  labels:
    app: k8s-ansible
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ansible
      component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-ansible
        component: mysql
    spec:
      restartPolicy: Always
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: k8s-ansible-mysql
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.28.4"
          command: 
            - rm
            - -fr
            - /var/lib/mysql/lost+found
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:5.7.22
          ports:
            - containerPort: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          envFrom:
            - configMapRef:
                name: k8s-ansible-mysql-env
            - secretRef:
                name: k8s-ansible-mysql-env
