---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-puma
  labels:
    app: k8s-ansible
    component: puma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ansible
      component: puma
  template:
    metadata:
      labels:
        app: k8s-ansible
        component: puma
    spec:
      restartPolicy: Always
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: k8s-ansible-uploads
      containers:
        - name: puma
          image: k8s_ansible/web:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          command:
            - ./kube/bin/start-puma
          # livenessProbe:
          #   httpGet:
          #     path: /health_check/full
          #     port: 3000
          #   initialDelaySeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /health_check/full
          #     port: 3000
          #   initialDelaySeconds: 30
          envFrom:
            - configMapRef:
                name: k8s-ansible-rails-env
            - secretRef:
                name: k8s-ansible-rails-env
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/public/uploads
