---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-redis
  labels:
    app: k8s-ansible
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ansible
      component: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-ansible
        component: redis
    spec:
      restartPolicy: Always
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: k8s-ansible-redis
      containers:
        - name: redis
          image: redis:4.0.10
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          envFrom:
            - secretRef:
                name: k8s-ansible-rails-env
