---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-sidekiq
  labels:
    app: k8s-ansible
    component: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ansible
      component: sidekiq
  template:
    metadata:
      labels:
        app: k8s-ansible
        component: sidekiq
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 65
      containers:
        - name: sidekiq
          image: k8s_ansible/web:1.0.0
          imagePullPolicy: IfNotPresent
          command:
            - ./kube/bin/start-sidekiq
          livenessProbe:
            exec:
              command:
                - ./kube/bin/health-check-sidekiq
            initialDelaySeconds: 30
          envFrom:
            - configMapRef:
                name: k8s-ansible-rails-env
            - secretRef:
                name: k8s-ansible-rails-env
