default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "0.0.0.0" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "mysql-secret" } %>
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: dmsm_k8s_ansible

test:
  <<: *default
  database: dmsm_k8s_ansible

production:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { "dmsm_k8s_ansible_production" } %>