---
apiVersion: v1
kind: Service
metadata:
  name: amz-selenium-web-mysql
  labels:
    app: amz-selenium-web
    component: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
  selector:
    app: amz-selenium-web
    component: mysql
  type: NodePort
