---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ansible-mysql
  labels:
    app: k8s-ansible
    component: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
  selector:
    app: k8s-ansible
    component: mysql
  type: NodePort
