---
apiVersion: v1
kind: Service
metadata:
  name: amz-selenium-web-puma
  labels:
    app: amz-selenium-web
    component: puma
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: amz-selenium-web
    component: puma
