---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ansible-redis
  labels:
    app: k8s-ansible
    component: redis
spec:
  ports:
    - protocol: TCP
      port: 6379
  selector:
    app: k8s-ansible
    component: redis
  type: NodePort
