---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-ansible-puma
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  # backend:
  #   serviceName: k8s-ansible-puma
  #   servicePort: 3000
  # tls:
  # - hosts:
  #   - k8s-ansible-puma.local
  #   secretName: k8s-ansible-puma-tls
  rules:
  - host: xincheng.today
    http:
      paths:
      - backend:
          serviceName: k8s-ansible-puma
          servicePort: 3000
        path: /
